### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by whitebarry** [yoda-pa/yoda#62] opened 2017-12-14 01:37 UTC
I forked, cloned, and followed the steps of making the venv and installing requirements with pip. There were no errors reported during the installation of requirements. When I run yoda I get an ImportError stating that there is no config module. I had to copy config.py(c) from the project root into the `site-packages\modules` folder. I then had the same issue with util.py(c). After that I was able to run yoda successfully.

As an aside, I find it unusual to see a package like this where you install the 'production' code and execute it i.e. `pip install .` I think it would be an improvement to move the dependencies to requirements.txt and have the instructions simply call out `pip install -r requirements.txt`. The problem this causes for me anyway, maybe I'm missing something obvious, is that when i make a change to the project code, I do not see that reflected by running `yoda`. It is also not obvious to me where the entry point of the app is if, for example, i wanted to run it from within my IDE or from the command line with `python <filename>.py`.

What are the steps to reproduce this issue?
-------------------------------------------
1. Make virtualenv
2. `pip install .`
3. `yoda`

What happens?
-------------
`  File "c:\users\barry\pycharmprojects\yoda\venv\yoda\lib\site-packages\modules\setup.py", line 13, in <module>
    from config import get_config_file_paths
ImportError: No module named config`

What were you expecting to happen?
----------------------------------
For yoda to run normally

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 7 Ultimate 64 bit
**Python version:** 2.7

**Comment by drugones** [comment] 2018-02-02 19:51
Same issue here on osx.

**Comment by JonSn0w** [comment] 2018-02-04 22:16
I'm also having this issue on macOS 10.12

**Comment by SillySam** [comment] 2018-02-05 10:33
Couldn't the "config" library just be added to the `requirements.txt` so that when users initially run `pip install -r requirements.txt` that It would download this missing package?
I haven't properly looked at the project, just stumbled across this issue, so I apologize If my suggestion is wrong.

**Comment by manparvesh** [comment] 2018-02-05 13:08
@SillySam `config.py` is actually a file in the root folder of this project, so what you're suggesting is infeasible. I'll investigate the cause.

**Comment by manparvesh** [comment] 2018-02-05 13:52
@whitebarry @drugones @JonSn0w @SillySam 
Thanks for reporting the issue and for the suggestions. I have fixed the issue, so I will close this issue

**Closed by manparvesh** 2018-02-05 13:52 UTC
Labels: bug, help wanted, high priority
